"""add scores and alter column id

Revision ID: 094a1b742127
Revises: 87e40c23c67b
Create Date: 2025-01-12 12:57:26.758692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094a1b742127'
down_revision: Union[str, None] = '87e40c23c67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('away_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'away_score')
    op.drop_column('matches', 'home_score')
    # ### end Alembic commands ###
