"""add match_id column and do refactor

Revision ID: 1febf8ec87fb
Revises: 094a1b742127
Create Date: 2025-01-13 19:07:27.932396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1febf8ec87fb'
down_revision: Union[str, None] = '094a1b742127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_id', sa.String(), nullable=False))
    op.drop_constraint('statistics_match_id_fkey', 'statistics', type_='foreignkey')
    op.alter_column("statistics", "match_id", existing_type=sa.Integer, type_=sa.String)
    op.create_unique_constraint("match_id_is_unique_accross_portals", 'matches',
                        ['match_id'])
    op.create_foreign_key("match_stats_connection", 'statistics', 'matches',
                 ['match_id'], ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("match_stats_connection", 'statistics', type_='foreignkey')
    op.create_foreign_key('statistics_match_id_fkey', 'statistics', 'matches',
                 ['match_id'], ['id'])
    op.drop_constraint("match_id_is_unique_accross_portals", 'matches', type_='unique')
    op.drop_column('matches', 'match_id')
    # ### end Alembic commands ###
