"""init models

Revision ID: 87e40c23c67b
Create Date: 2025-01-09 15:13:32.053435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import CreateSequence, Sequence, DropSequence

# revision identifiers, used by Alembic.
revision: str = '87e40c23c67b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence("match_id")))
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('stadium', sa.String(), nullable=True),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('away', sa.String(), nullable=True),
    sa.Column('referee', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('home', sa.Float(), nullable=True),
    sa.Column('away', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics', cascade=True)
    op.drop_table('matches', cascade=True)
    op.execute(DropSequence('match_id'))
    # ### end Alembic commands ###
