# debug mode
debug: true
# selection of currently used database
db: postgresql
# publisher socket where from to get data
publisher:
  host: 127.0.0.1
  port: 43200
# name of the service for specific topic
# semantic of data is divided by topic
services:
  - name: match_processing
    topic: sofascore.events

  - name: statistics_processing
    topic: sofascore.stats
