# selection of currently used database
db: postgresql
# publisher socket where from to get data
publisher:
  host: 127.0.0.1
  port: 43211
# name of the service for specific topic
# semantic of data is divided by topic
services:
  - name: health_check
    topic: footystats
  - name: health_check
    topic: health
