db: postgresql
sockets:
  - topic: footystats
    sockopts:
      - XXX high water mark set here for example
  - topic: flashscore
    sockopts:
      -
processors:
  - topic: flashscore.*
    module: flashscore