db:
  sqlite:
    path: ":memory:"
    dbname: "test"
  postgresql:
    dbname: "swtdb"
    host: localhost
    port: 5432
    user: postgres
    password: usmiechnieci123
# docker uruchomiony z takim hasłem.
